### PR TITLE
Fix typo in the BROWSERSTACK_USERNAME env var

### PR DESCRIPTION
**Pull request by tchia04**
From https://www.browserstack.com/automate/cucumber-integration,
The correct syntax is BROWSERSTACK_USERNAME not BROWSERSTACK_USER_NAME

RUN_ON_BSTACK=true BROWSERSTACK_USERNAME=USERNAME BROWSERSTACK_ACCESS_KEY=ACCESS_KEY bundle exec cucumber

### CODE REVIEW

**Comment by taktakpeops** [comment]
Hi, please, update the README the same way. 

It will also require an update of the CI/CD before being merged

**Comment by tchia04** [comment]
I have updated in all places except for secrets.BROWSERSTACK_USER_NAME which should not impact the end user.

**Comment by taktakpeops** [comment]
Thank you for the update. However, for consistency, could you also update the YAML files?

Once it's done, I will merge it and release it

**Comment by tchia04** [comment]
I have renamed the secret key to secrets.BROWSERSTACK_USERNAME
Please make sure a secret key with that name exists so the build doesn't fail.

**Comment by taktakpeops** [comment]
Thank you. It will be merged in the evening

**Pull request merged**
